### ISSUE TITLE
Prompt for login / auto login / pretty auth error message

### ISSUE THREAD

**Issue by joegoldin** [davidhu2000/kube-knots#279]
Awesome app!

### Description

It'd be great if the "Uh oh" error message on launch, when you're not authenticated with AWS/k8s, triggered a prompt to login or ran an automatic login command. 

### Use Cases

App open when not authed to k8s

### Would you be interestined in implementing this feature yourself?

- [ ] Yes, I am interested in implementing this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidhu2000** [comment]
the backend just returns the error as a string which making error handling pretty easy. do agree that it could look better. 

The hard part will be figuring out all the commands we need to run to authorize, like for AWS between sso or saml. 

I'd guess it might work if we pull the Kubeconfig and look at the command. 

```yaml
users:
  - name: arn:aws:eks:us-west-2:1234:cluster/not-real
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - us-west-2
          - eks
          - get-token
          - --cluster-name
          - not-real
        command: /usr/local/bin/aws
```

I see something like this in kubeconfig. so we could pull the command needed to run. and at least allow the user to simply copy paste it into their terminal, if we can't run it ourselves. 

The token actually do get auto refreshed, when it errors out, usually that means we need some manual intervention.
